on:
  workflow_dispatch:
  workflow_run:
    workflows: [ Checks ]
    types: [ completed]
    branches: [ master ]

name: "Release"

jobs:
  release-dev:
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') }}
    uses: ./.github/workflows/release_dev.yml
    secrets: inherit

  release-prod:
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') }}
    needs: release-dev
    uses: ./.github/workflows/release_prod.yml
    secrets: inherit
